/* Elya adaptation: Codex / GPT / 模型 ID 无法确认. Source: Wallpaper Engine 3807744786. */
'use strict';
/* ============================================================
   英文对照表：键是页面里的中文原文，值是英文
   {n} 这样的是占位符；值也可以是函数，拿到占位符的值自己拼（单复数之类）
   新加中文文字时记得在这里补上，js/i18n.js 的 missingText() 能列出漏掉的
   ============================================================ */
const plural = (n, one, many) => `${n} ${+n === 1 ? one : many}`;

const EN = {
  // 页面和面板
  '锦鲤池': 'Koi Pond',
  '打开设置': 'Open settings',
  '轻点水面撒一把鱼食 · 右上角可以调景致和天气': 'Tap the water to scatter food · Settings are at the top right',
  '轻点水面撒一把鱼食': 'Tap the water to scatter food',
  '池畔设置': 'Pond Settings',
  '关闭设置': 'Close settings',
  '景致': 'Scene',
  '天气': 'Weather',
  '我的锦鲤': 'My Koi',
  '图鉴': 'Journal',

  '画面': 'Visuals',
  '画风': 'Style',
  '清透': 'Clear',
  '水彩': 'Watercolor',
  '按钮': 'Button',
  '一直显示': 'Always',
  '鼠标靠近时': 'On hover',
  '纸纹': 'Paper',
  '光斑': 'Light',
  '语言': 'Language',
  '池中': 'In the pond',
  '锦鲤': 'Koi',
  '游速': 'Speed',
  '乌龟': 'Turtles',
  '蝴蝶蜻蜓': 'Butterflies',
  '青蛙': 'Frogs',
  '花叶': 'Petals',
  '时钟': 'Clock',
  '声音': 'Sound',
  '环境音': 'Ambience',
  '音量': 'Volume',
  '水声、雨声、雷声、蛙鸣、夜里的虫鸣，还有撒食、水花的声音，全部由程序实时合成。':
    'Water, rain, thunder, frogs, crickets at night, food and splashes — every sound is synthesized live.',
  '性能': 'Performance',
  '帧率': 'FPS',
  '自动': 'Auto',
  '30 省电': '30 Saver',
  '60 流畅': '60 Smooth',
  '画质': 'Quality',
  '高': 'High',
  '省电': 'Saver',
  '帧率选“自动”时，有动静就跑 60 帧，池子安静下来降到 30 帧。画质选“自动”时，电脑跟不上会自动把分辨率降一档。':
    'With FPS on Auto, it runs at 60 while things move and drops to 30 when the pond is calm. With Quality on Auto, resolution steps down if your PC can\'t keep up.',

  '实时': 'Live',
  '晴': 'Clear',
  '多云': 'Cloudy',
  '雨': 'Rain',
  '雷雨': 'Storm',
  '雪': 'Snow',
  '雾': 'Fog',
  '城市': 'City',
  '搜索': 'Search',
  '输入城市名，比如 London': 'e.g. Tokyo',
  '查找': 'Find',
  '时段': 'Time of day',
  '跟随时间': 'Follow clock',
  '白天': 'Day',
  '黄昏': 'Dusk',
  '夜晚': 'Night',
  '季节': 'Season',
  '跟随日期': 'Follow date',
  '春': 'Spring',
  '夏': 'Summer',
  '秋': 'Autumn',
  '冬': 'Winter',
  '影子跟着太阳走，早晚长、正午短。春天岸边的树会落花，夏天荷花开，秋天结莲蓬、落叶，冬天是残荷，最冷的日子池边结冰。夜里看得到星星和当天真实的月相。南半球的城市，季节会自动反过来。':
    'Shadows follow the sun — long in the morning and evening, short at noon. In spring the tree by the shore sheds blossoms, summer brings lotus flowers, autumn seed pods and falling leaves, winter withered lotus and ice on the coldest days. At night you\'ll see stars and the real phase of the moon. Seasons flip automatically for southern-hemisphere cities.',

  '成长': 'Growth',
  '体长': 'Length',
  '吃过': 'Eaten',
  '陪伴': 'Together',
  '领养于': 'Adopted',
  '名字': 'Name',
  '换一个': 'Shuffle',
  '桌面上打不了字：点「换一个」随机挑名字，或者在壁纸软件的属性栏里填「我的锦鲤名字」。': "Typing doesn't work on the desktop: tap Shuffle for a random name, or fill in “My koi's name” in the wallpaper app's properties.",
  '桌面上打不了字：在壁纸软件的属性栏里填「其他城市」。': "Typing doesn't work on the desktop: fill in “Other city” in the wallpaper app's properties.",
  '品种': 'Variety',
  '自己画': 'Paint',
  '画布：在锦鲤身上涂抹，画出花纹': 'Canvas: paint a pattern on your koi',
  '颜色': 'Color',
  '底色': 'Base',
  '笔刷': 'Brush',
  '细': 'Fine',
  '中': 'Medium',
  '粗': 'Bold',
  '撤销': 'Undo',
  '清空': 'Clear all',
  '画好了，去看看': 'Done — go see it',
  '在鱼身上涂抹就是花纹，涂到身体外面的会被裁掉。每画一笔，池子里的它就跟着换上，游起来花纹会随身体弯。':
    'Paint on the body to make a pattern; anything outside the body is trimmed. Each stroke shows up on your koi right away, and the pattern bends as it swims.',
  '标记': 'Marker',
  '找找它': 'Find it',
  '唤它过来': 'Call it over',
  '重新领养': 'Adopt again',
  '再点一次，换一条新的': 'Tap again to adopt a new one',
  '它吃到的鱼食、你开着壁纸的时间，都会让它慢慢长大。点一下它会冒出小爱心。':
    'It slowly grows with every pellet it eats and every hour the wallpaper runs. Tap it and little hearts pop out.',
  '幼鱼': 'Fry',
  '正在长大': 'Growing',
  '成鱼': 'Adult',
  '池中老鲤': 'Pond elder',
  '自己画的': 'Hand-painted',
  '自己画的花纹': 'Hand-painted pattern',
  '{h} 小时 {m} 分': '{h} h {m} min',
  '{m} 分钟': '{m} min',
  '{n} 厘米': '{n} cm',
  '{n} 粒': v => plural(v.n, 'pellet', 'pellets'),
  '自动 {n}': 'Auto {n}',

  '池中之最': 'Pond records',
  '奇遇': 'Moments',
  '点一条纪录，池子里会把那条鱼圈出来。鼠标在一条鱼身上停一会儿，也能看到它的名字。稀有品种只会作为客人来访，见过以后就能给自己的锦鲤换上。':
    'Tap a record to circle that fish in the pond. Rest the cursor on a fish to see its name. Rare varieties only come as visitors — once you\'ve seen one, your own koi can wear it.',
  '最大的鱼': 'Biggest',
  '最小的鱼': 'Smallest',
  '最能吃': 'Hungriest',
  '最稀有': 'Rarest',
  '还没开饭': 'Not fed yet',
  '{label}：{name}，{kind}，{val}。在池中圈出它': '{label}: {name}, {kind}, {val}. Circle it in the pond',
  '池中 {n} 条 · 一共吃了 {e} 粒 · 来过 {v} 位客人': v => `${plural(v.n, 'fish', 'fish')} · ${plural(v.e, 'pellet', 'pellets')} eaten · ${plural(v.v, 'visitor', 'visitors')}`,
  '，留下 {g} 位': ', {g} stayed',
  '？？？': '???',
  '{name} · {day}第一次见到': '{name} · first seen {day}',
  '只会作为客人来访': 'Only comes as a visitor',
  '还没在池子里见过': 'Not seen in the pond yet',
  '{day} · {n} 次': v => `${v.day} · ${plural(v.n, 'time', 'times')}`,
  '常见': 'Common',
  '少见': 'Uncommon',
  '稀有': 'Rare',
  '传说': 'Legendary',

  // 提示条
  '图鉴新增': 'New!',
  '有客来访': 'A visitor',
  '悄悄话': 'Psst',
  '喂它些吃的，说不定它会留下': 'Feed it and it might stay',
  '池中小记': 'Pond moment',
  '鱼跃龙门': 'Dragon Gate',
  '{name}化作点点金光，不见了': '{name} turned into golden sparks and vanished',
  '留下来了': 'It stayed!',
  '{kind}住进了池子，就叫它「{name}」吧': '{kind} moved into the pond. Let\'s call it "{name}"',

  // 奇遇
  '撒一把鱼食': 'Scatter food',
  '轻点水面': 'Tap the water',
  '群鱼争食': 'Feeding frenzy',
  '连着多撒几把': 'Scatter food a few times in a row',
  '伸手入水': 'Hand in the water',
  '按住水面，别松手': 'Press and hold on the water',
  '划水': 'Stir the water',
  '在水面上拖一拖': 'Drag across the water',
  '锦鲤跃水': 'Leaping koi',
  '耐心等等，或者让它们吃得热闹些': 'Be patient, or give them a lively meal',
  '比心': 'Love you',
  '点点你自己的那条': 'Tap your own koi',
  '缩头乌龟': 'Shy turtle',
  '碰一碰乌龟': 'Poke a turtle',
  '乌龟回眸': 'A turtle looks back',
  '在乌龟旁边停一停': 'Rest the cursor next to a turtle',
  '扑通': 'Plop!',
  '荷叶上蹲着谁？': 'Who\'s sitting on the lily pad?',
  '蜻蜓点水': 'Dragonfly dip',
  '晴好的天气里留意水面': 'Watch the surface on a fine day',
  '蝶栖荷上': 'Butterfly at rest',
  '晴天的白天': 'A sunny day',
  '傍晚时分': 'Around sunset',
  '流萤': 'Fireflies',
  '天黑以后': 'After dark',
  '听雨': 'Listening to rain',
  '下雨的时候': 'When it rains',
  '惊雷': 'Thunderclap',
  '雷雨天': 'In a thunderstorm',
  '初雪': 'First snow',
  '下雪的时候': 'When it snows',
  '烟波': 'Misty water',
  '起雾的时候': 'When it\'s foggy',
  '河灯': 'River lanterns',
  '节日的夜里': 'On a festival night',
  '雨后彩虹': 'Rainbow after rain',
  '雨停了，太阳出来的时候': 'When the sun comes out after rain',
  '星河倒影': 'Starry reflection',
  '晴朗的夜里': 'On a clear night',
  '水中捞月': 'Scooping the moon',
  '晴夜里，碰一碰水里的月亮': 'On a clear night, touch the moon in the water',
  '落英': 'Falling blossoms',
  '春天，留意岸边那棵树': 'In spring, watch the tree by the shore',
  '一叶知秋': 'First autumn leaf',
  '秋天起风的时候': 'When the autumn wind picks up',
  '薄冰': 'Thin ice',
  '冬天最冷的日子': 'On the coldest winter days',
  '鹭影': 'Egret\'s shadow',
  '晴天里，留意掠过水面的影子': 'On a sunny day, watch for a shadow gliding over',
  '开着壁纸，总会有客人来': 'Keep the wallpaper running and guests will come',
  '留客': 'A guest stays',
  '客人来了，喂它些吃的': 'Feed a visiting guest',
  '最稀有的客人，走的时候不一样': 'The rarest guest leaves in a special way',

  // 天气
  '晴间多云': 'Partly cloudy',
  '阴': 'Overcast',
  '毛毛雨': 'Drizzle',
  '小雨': 'Light rain',
  '中雨': 'Moderate rain',
  '大雨': 'Heavy rain',
  '冻雨': 'Freezing rain',
  '小雪': 'Light snow',
  '中雪': 'Moderate snow',
  '大雪': 'Heavy snow',
  '雷阵雨': 'Thunderstorm',
  '雷雨冰雹': 'Thunderstorm, hail',
  '今天': 'Today',
  '明天': 'Tomorrow',
  '后天': () => new Date(Date.now() + 2 * 864e5).toLocaleDateString('en-US', { weekday: 'long' }),
  '手动 · {w}': 'Manual · {w}',
  '现在是手动天气。选“实时”会按所选城市的真实天气变化。': 'Weather is set by hand. Pick "Live" to follow the real weather in your city.',
  '{city} · {w} · {temp}°C': '{city} · {w} · {temp}°C',
  '{time} 更新 · 每半小时刷新 · 数据来自 Open-Meteo': 'Updated {time} · refreshes every 30 min · data from Open-Meteo',
  '{city} · 正在获取天气': '{city} · Loading weather',
  '正在连接 Open-Meteo……': 'Connecting to Open-Meteo…',
  '{city} · 天气未连接': '{city} · Weather offline',
  '连不上天气服务，先按晴天显示。在预览页里这是正常的，因为预览页不能访问外部网络；放到 Lively 里用就能连上。也可以直接手动选一种天气。':
    'Can\'t reach the weather service, so it shows clear skies for now. That\'s normal in previews without internet access. You can also pick a weather by hand.',
  '正在查找……': 'Searching…',
  '没找到这个城市': 'City not found',
  '查不到，网络不通': 'Search failed — no connection',
  '已切换到 {city}': 'Now showing {city}',

  // 画锦鲤
  '绯红': 'Scarlet',
  '墨黑': 'Ink black',
  '雪白': 'Snow white',
  '金黄': 'Gold',
  '橙': 'Orange',
  '浅葱蓝': 'Asagi blue',
  '白': 'White',
  '墨': 'Ink',
  '黄金': 'Gold',
  '白金': 'Platinum',
  '绯': 'Scarlet',
  '浅葱': 'Pale blue',
  '茶': 'Brown',
  '{c}底': '{c} base',
  '橡皮': 'Eraser',
  '画满了，擦掉一些再画': 'The canvas is full — erase some to keep painting',

  // 节日
  '中秋': 'Mid-Autumn',
  '春节': 'Lunar New Year',
  '元宵': 'Lantern Festival',
  '除夕': 'New Year\'s Eve',
  '中秋快乐 · 天黑以后，池子里会漂起河灯': 'Happy Mid-Autumn Festival · Lanterns float on the pond after dark',
  '新春快乐 · 夜里会有红灯笼漂过': 'Happy Lunar New Year · Red lanterns drift by at night',
  '元宵快乐 · 今晚池子里有花灯': 'Happy Lantern Festival · Lanterns on the pond tonight',
};

// 锦鲤品种（用日本锦鲤的通用叫法）和池里鱼的名字；和上面分开，免得和节气、天气撞名
const EN_NAMES = {
  '红白': 'Kohaku', '丹顶': 'Tancho', '大正三色': 'Taisho Sanke', '昭和三色': 'Showa Sanshoku',
  '黄金': 'Yamabuki Ogon', '白金': 'Platinum Ogon', '绯鲤': 'Higoi', '茶鲤': 'Chagoi', '乌鸦': 'Karasu',
  '秋翠': 'Shusui', '九纹龙': 'Kumonryu', '白写': 'Shiro Utsuri', '孔雀': 'Kujaku', '松叶': 'Matsuba',
  '银鳞红白': 'Ginrin Kohaku', '落叶时雨': 'Ochiba Shigure', '五色': 'Goshiki', '浅黄': 'Asagi',
  '金鳞': 'Golden Scale', '金龙鲤': 'Golden Dragon', '自绘': 'Hand-painted',
  '小锦': 'Kiki',
  '阿福': 'Lucky', '元宝': 'Nugget', '团团': 'Roly', '汤圆': 'Tangyuan', '年糕': 'Ricecake', '花卷': 'Twist',
  '豆沙': 'Bean', '芝麻': 'Sesame', '布丁': 'Pudding', '栗子': 'Chestnut', '糯米': 'Sticky', '米粒': 'Rice',
  '丸子': 'Dumpling', '桂圆': 'Longan', '红豆': 'Adzuki', '麻薯': 'Mochi', '可可': 'Cocoa', '奶茶': 'Boba',
  '橘子': 'Tangerine', '柚子': 'Yuzu', '青梅': 'Plum', '杏仁': 'Almond', '核桃': 'Walnut', '小满': 'Brimful',
  '谷雨': 'Drizzle', '白露': 'Dewdrop', '朝朝': 'Dawn', '暮暮': 'Twilight', '点点': 'Dot', '墨墨': 'Inky',
  '阿金': 'Goldie', '阿银': 'Silver', '大红': 'Big Red', '胖胖': 'Chubby', '圆圆': 'Button', '泡泡': 'Bubbles',
  '波波': 'Ripple', '鼓鼓': 'Puffy', '悠悠': 'Drifty', '慢慢': 'Slowpoke', '跳跳': 'Hopper', '闹闹': 'Rowdy',
  '乐乐': 'Joy', '福福': 'Fortune', '旺旺': 'Buddy', '如意': 'Wish', '吉祥': 'Charm', '锦儿': 'Nishiki',
  '胭脂': 'Rouge', '丹丹': 'Scarlet', '雪球': 'Snowball', '樱桃': 'Cherry', '荔枝': 'Lychee', '山楂': 'Hawthorn',
  '酒酿': 'Sake', '汤包': 'Bao', '馒头': 'Bun', '烧卖': 'Shumai', '月饼': 'Mooncake', '粽子': 'Zongzi',
  '蛋黄': 'Yolk', '云朵': 'Cloud', '石榴': 'Garnet', '枇杷': 'Loquat', '海棠': 'Begonia', '小鲤': 'Koko',
  '大头': 'Bighead',
};

// 二十四节气
const EN_TERMS = {
  '小寒': 'Minor Cold', '大寒': 'Major Cold', '立春': 'Start of Spring', '雨水': 'Rain Water',
  '惊蛰': 'Awakening of Insects', '春分': 'Spring Equinox', '清明': 'Clear and Bright', '谷雨': 'Grain Rain',
  '立夏': 'Start of Summer', '小满': 'Grain Buds', '芒种': 'Grain in Ear', '夏至': 'Summer Solstice',
  '小暑': 'Minor Heat', '大暑': 'Major Heat', '立秋': 'Start of Autumn', '处暑': 'End of Heat',
  '白露': 'White Dew', '秋分': 'Autumn Equinox', '寒露': 'Cold Dew', '霜降': 'Frost\'s Descent',
  '立冬': 'Start of Winter', '小雪': 'Minor Snow', '大雪': 'Major Snow', '冬至': 'Winter Solstice',
};
